// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elbgjrnrqrefkqyraavw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsYmdqcm5ycXJlZmtxeXJhYXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDU0NzUsImV4cCI6MjA2MDkyMTQ3NX0.pzZ6CgTcjT0Qy7RpzUHkYRXQ0hL_FgsqJiwQYGAm-YY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);